"use strict";
exports.__esModule = true;
var fs_1 = require("fs");
var Const_1 = require("./Const");
var Utils_1 = require("./Utils");
var BuildUserDataEvent = /** @class */ (function () {
    function BuildUserDataEvent() {
        this.build();
    }
    BuildUserDataEvent.prototype.build = function () {
        if ((0, fs_1.existsSync)(Const_1.UserDataPath) == false)
            return console.error("文件不存在=>" + Const_1.UserDataPath);
        var content = (0, fs_1.readFileSync)(Const_1.UserDataPath).toString();
        var startIndex = content.indexOf("interface IUserData");
        if (startIndex == -1)
            return console.error("没有找到IUserData");
        var endIndex = content.indexOf("}", startIndex);
        var data = content.substring(startIndex, endIndex);
        var matches = data.match(/.*;/g).map(function (match) { return match.trim().split(":")[0].replace("?", ""); });
        var result = "/**The class is automatically generated by BatMain.bat , please do not modify */\nexport const enum UserDataEvent {\n";
        matches.forEach(function (v) { return result += "\t".concat((0, Utils_1.UpperFirst)(v), "_Changed = \"").concat((0, Utils_1.UpperFirst)(v), "_Changed\",\n"); });
        result += "}";
        (0, fs_1.writeFileSync)(Const_1.UserDataEventPath, result);
    };
    return BuildUserDataEvent;
}());
exports["default"] = BuildUserDataEvent;
