"use strict";
exports.__esModule = true;
exports.LangPath = exports.TableStructTypePath = exports.TablesCfgDir = exports.TableDataPath = exports.xlsxDir = exports.ViewRegisterPath = exports.ViewIDPath = exports.ResPathPathNoExt = exports.ResPathPath = exports.ViewCtrlDir = exports.ViewDir = exports.UiDir = exports.ResDir = exports.__workname = void 0;
var path_1 = require("path");
exports.__workname = process.cwd();
exports.ResDir = (0, path_1.resolve)(exports.__workname, "bin/res");
exports.UiDir = (0, path_1.resolve)(exports.__workname, "src/core/ui/ui");
exports.ViewDir = (0, path_1.resolve)(exports.__workname, "src/core/ui/view");
exports.ViewCtrlDir = (0, path_1.resolve)(exports.__workname, "src/core/ui/viewCtrl");
exports.ResPathPath = (0, path_1.resolve)(exports.__workname, "src/core/common/ResPath.ts");
exports.ResPathPathNoExt = (0, path_1.resolve)(exports.__workname, "src/core/common/ResPath");
exports.ViewIDPath = (0, path_1.resolve)(exports.__workname, "src/core/ui/core/ViewID.ts");
exports.ViewRegisterPath = (0, path_1.resolve)(exports.__workname, "src/core/ui/core/ViewRegister.ts");
exports.xlsxDir = (0, path_1.resolve)(exports.__workname, "../策划");
exports.TableDataPath = (0, path_1.resolve)(exports.__workname, "bin/res/table/Config.json");
exports.TablesCfgDir = (0, path_1.resolve)(exports.__workname, "src/core/table");
exports.TableStructTypePath = (0, path_1.resolve)(exports.__workname, "src/core/table/TableStructTypes.d.ts");
exports.LangPath = (0, path_1.resolve)(exports.__workname, "src/core/table/LangCode.ts");
