import { existsSync, readFileSync, writeFileSync } from "fs";
import { UserDataEventPath, UserDataPath } from "./Const";
import { UpperFirst } from "./Utils";

export default class BuildUserDataEvent {
    constructor() {
        this.build();
    }

    private build(){
        if(existsSync(UserDataPath) == false) return console.error("文件不存在=>" + UserDataPath);
        const content = readFileSync(UserDataPath).toString();
        const startIndex = content.indexOf("interface IUserData");
        if(startIndex == -1) return console.error("没有找到IUserData");
        const endIndex = content.indexOf("}", startIndex);
        const data = content.substring(startIndex, endIndex);
        const matches = data.match(/.*;/g).map(match => match.trim().split(":")[0].replace("?", ""));
        let result = "/**The class is automatically generated by BatMain.bat , please do not modify */\nexport const enum UserDataEvent {\n";
        matches.forEach(v => result += `\t${UpperFirst(v)}_Changed = "${UpperFirst(v)}_Changed",\n`);
        result += "}";
        writeFileSync(UserDataEventPath, result);
    }
}